# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/purpose': '@stable'
    'libraries/kirigami-addons': '@latest'

Options:
  require-passing-tests-on: [ 'Linux' ]
